### ISSUE TITLE
Combining BBOX or SEGS?

### ISSUE THREAD

**Issue by Sorry-Im-Stupid** [badjeff/comfyui_lora_tag_loader#12]
I've been wondering if there's a way to load multiple BBOX Uralytics nodes into the same simple detector node, or at least to load them in sequence without having to re-load the SAM or controlnet model for every box detector.

The way I've seen it done is very inefficient and always ends up filling up my RAM, which usually ends up crashing.

**Comment by badjeff** [comment]
Are you sure this is the correct place to ask BBOX nodes?

**Comment by Sorry-Im-Stupid** [comment]
Is it not? Oh damn I'm in the wrong project. Sorry for that.

 Egg on my face.
