### ISSUE TITLE
Is this compatible with the autocomplete?

### ISSUE THREAD

**Issue by TomLucidor** [badjeff/comfyui_lora_tag_loader#3]
The package in question https://github.com/pythongosssss/ComfyUI-Custom-Scripts

**Comment by TomLucidor** [comment]
Side note: it is not recognizing LoRAs when used within Stability Matrix https://github.com/LykosAI/StabilityMatrix

**Comment by badjeff** [comment]
AFAIK, it doesn't scan lora folders. it needed to be defined in custom word list manually.

**Comment by TomLucidor** [comment]
Yeah I guess this is time to automate word list fixing, since it does make entering info a bit easier, would the two autocomplete feature clash with one another (assuming LoRA tag loader does this)?

Note: I am using Stability Matrix so the LoRA folder should hopefully be stable in one place

**Comment by badjeff** [comment]
[rgthree-comfy](https://github.com/rgthree/rgthree-comfy) Power Prompt can scan Lora folders and gen the tag. but the trigger prompt is not available from any node yet, no solution out there as I know.
