### ISSUE TITLE
Doesn't work as intended with subfolders

### ISSUE THREAD

**Issue by dchatel** [badjeff/comfyui_lora_tag_loader#4]
If you use subfolders in your lora, using <lora:folder/some_lora:0.8:0.7> won't be parsed, resulting in the lora not being loaded.

**Comment by badjeff** [comment]
It picks file in all subfolders by unique filename. The 'folder' segment in tag string is ignored to emulate lora selection in automatic1111/stable-diffusion-webui

**Comment by dchatel** [comment]
I mean, recently, https://github.com/pythongosssss/ComfyUI-Custom-Scripts autocomplete feature got updated to also auto complete loras, and it uses this syntax: &lt;lora:folder/some_lora:0.8:0.7&gt;
I noticed that if I leave it like that, the lora won't load. If, instead, I use soma_lora only instead of folder/some_lora in that syntax, then it will load.

**Comment by badjeff** [comment]
For this node, if the lora located at 'style/food/CroissantStyle.safetensors', it can load path on below.
```log
detected lora tag: ('lora', 'CroissantStyle', '1', '1') >> style/food/CroissantStyle.safetensors
detected lora tag: ('lora', 'style/food/CroissantStyle', '1', '1') >> style/food/CroissantStyle.safetensors
detected lora tag: ('lora', 'CroissantStyle.safetensors', '1', '1') >> style/food/CroissantStyle.safetensors
detected lora tag: ('lora', 'style/food/CroissantStyle.safetensors', '1', '1') >> style/food/CroissantStyle.safetensors
```

**Comment by dchatel** [comment]
I made a mistake when reporting this issue. My comfyui is on a windows system. Bbasically, the line 12 of nodes.py needs to be changed to the following (added 4 \ at :
```python
self.tag_pattern = "\<[0-9a-zA-Z\:\_\-\.\s\/\(\)\\\\]+\>"
```
or alternatively, you can use this to make it a bit more readable:
```python
self.tag_pattern = r"<[0-9a-zA-Z:_\-.\s/()\\]+\>"
```
Finally, there are some other custom nodes that make use of the syntax `<something...>`, in particular https://github.com/asagi4/comfyui-prompt-control makes use of the syntax `<emb:xyz>` as an alternative for `embedding:xyz`, to avoid a conflict with `[embedding:xyz:0.5]`.
So, your custom node isn't compatible as is, with custom nodes similar to comfyui-prompt-control.
But, you can easily fix the issue by modifying line 12:
```python
self.tag_pattern = r"<lora:[0-9a-zA-Z:_\-.\s/()\\]+\>"
```

**Comment by badjeff** [comment]
Thanks mate. I never thought that before.
