### ISSUE TITLE
LORA Stack Output?

### ISSUE THREAD

**Issue by darkpixel** [badjeff/comfyui_lora_tag_loader#5]
I would love to see it output a LORA Stack so the extracted LORAs and weights could be fed into "Efficient Loader".

It would make it easier to paste in a prompt that contains several LORAs, remove one of the LORA definitions and then feed everything into an XY Plot so you can tune and balance the one LORA you removed.

**Comment by badjeff** [comment]
Could you share a workflow of your case? Maybe leave a note in the workflow to point out the node you want it be emulated.

**Comment by darkpixel** [comment]
It's a fairly complex workflow...but basically I dynamically generate prompts from text files that include ```<lora:xyz>``` tags and see what gets spit out.

Pseudo-wildcard prompt style:
```a __person__ wearing __clothing__ with __eyes__``` might translate into:
```a <lora:soldier:0.8> soldier wearing a <lora:sillyhats:0.8> tophat with blue eyes```.

But occasionally I want to figure out what strength is best for one of the LORAs...so I might change the prompt to:
```a __person__ wearing a tophat with __eyes__``` which would translate to:
```a <lora:soldier:0.8> soldier wearing a tophat with blue eyes```.

If the tag loader spit out a LORA Stack that contained the 'soldier' LORA, I could feed that into an XY Plot with the 'sillyhats' LORA to generate an array of the different model/clip weights.

I grabbed a copy of your tag loader and implemented here for my workflow:
https://github.com/darkpixel/darkprompts/blob/766ed43826a1abed8d2fd3c269fc0f60f960cd88/gpl3/__init__.py#L97

If you're amenable to the changes, I can submit a PR.

**Comment by badjeff** [comment]
There is a code-free approach. https://youtu.be/nU3vZBzeWpQ?t=104

**Comment by darkpixel** [comment]
Sure--I just don't want to have to create a whole new workflow (and copy/paste various prompts) to do a search/replace.  I'd rather dynamically generate the prompts minus one specific LORA and test against it under various prompt conditions.  I can just auto-queue it and get a bunch of grids and compare them all to find the best weight.

**Comment by alexqem** [comment]
Can't input by workflow .png
