### ISSUE TITLE
Prompt as text input

### ISSUE THREAD

**Issue by Ariloum** [badjeff/comfyui_lora_tag_loader#9]
Hey, where can I find version with prompt connectible as text input like on your screenshot on the main page?
I'd like to combine it with the dynamic prompt but with current state and inclusive textboxes they won't love each other.

![2024-06-23 00_18_57-ComfyUI](https://github.com/badjeff/comfyui_lora_tag_loader/assets/6816952/8c92e25d-8b97-4d05-bfae-b34b944234a7)

**Comment by badjeff** [comment]
https://github.com/badjeff/comfyui_lora_tag_loader/issues/1#issuecomment-1679955074

**Comment by Ariloum** [comment]
> [#1 (comment)](https://github.com/badjeff/comfyui_lora_tag_loader/issues/1#issuecomment-1679955074)

That's nice to know, thank you mate
